title: Laura Brooks ePortfolio
description: A showcase of work used to highlight a special set of skills!
theme: just-the-docs

url: https://sourkrouse.github.io/ePortfolio/
color_scheme: dark

aux_links:
  Weight and See App Repository: https://github.com/sourkrouse/ePortfolio/tree/master

  
